baseURL = "https://ar-us.com/"
description = "We know valve failures rarely happen at convenient times. Which is why we pride ourselves on having the best customer service. Whether it’s at 2pm or 2am, we’re ready when you are."
enableRobotsTXT = true
languageCode = "en-us"
theme = "site-theme"
title = "A+R Valve USA, LLC"
[[menu.desktop]]
identifier = "Metal Seated"
name = "Metal Seated"
url = "/"
weight = 1
[[menu.desktop]]
identifier = "KHF 710"
name = "KHF 710"
parent = "Metal Seated"
url = "/khf-710-metal-seated/"
weight = 1
[[menu.desktop]]
identifier = "Soft Seated"
name = "Soft Seated"
url = "/soft-seated"
weight = 2
[[menu.desktop]]
identifier = "KHL 510"
name = "KHL 510"
parent = "Soft Seated"
url = "/khl-510-soft-seated/"
weight = 1
[[menu.desktop]]
identifier = "KHF 710 Soft"
name = "KHF 710"
parent = "Soft Seated"
url = "/khf-710-soft-seated/"
weight = 2
[[menu.desktop]]
identifier = "About Us"
name = "About Us"
url = "/about-us/"
weight = 3
[[menu.desktop]]
identifier = "Contact Us"
name = "Contact Us"
url = "/contact-us/"
weight = 4
[[menu.mobile]]
identifier = "Metal Seated"
name = "Metal Seated"
url = "/metal-seated"
weight = 1
[[menu.mobile]]
identifier = "KHF 710"
name = "KHF 710"
parent = "Metal Seated"
url = "/khf-710-metal-seated/"
weight = 1
[[menu.mobile]]
identifier = "Soft Seated"
name = "Soft Seated"
url = "/soft-seated"
weight = 2
[[menu.mobile]]
identifier = "KHL 510"
name = "KHL 510"
parent = "Soft Seated"
url = "/khl-510-soft-seated/"
weight = 1
[[menu.mobile]]
identifier = "KHF 710 Soft"
name = "KHF 710"
parent = "Soft Seated"
url = "/khf-710-soft-seated/"
weight = 2
[[menu.mobile]]
identifier = "About Us"
name = "About Us"
url = "/about-us/"
weight = 3
[[menu.mobile]]
identifier = "Contact Us"
name = "Contact Us"
url = "/contact-us/"
weight = 4
[outputFormats.sitemapindex]
baseName = "sitemapindex"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.sitepages]
baseName = "sitepages"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.siteposts]
baseName = "siteposts"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputs]
home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS"]
[params.publishing_settings]
site_in_production = true
[params.social_links]
facebook = ""
insta = ""
linkedin = ""
pinterest = ""
[params.tracking]
cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"
google_analytics = ""
[params.utility_images]
thank_you_background = "/pageimg/thank-you-contact.jpg"
[sitemap]
filename = "sitepages.xml"
